language: node_js
node_js:
  - "node"
cache:
  directories:
    - node_modules
    - dev-portal/node_modules
install:
  - cd dev-portal && yarn install
script:
  - cd dev-portal
  - CI=true yarn test
  - yarn build
