---
swagger: "2.0"
info:
  description: "Service that provides dietary reference values compiled by EuroFIR."
  version: "1.0.0"
  title: "EuroFIR-DietaryReferenceValues"
host: "api.quisper.eu"
basePath: "/dietary-reference-values/beta"
schemes:
- "https"
paths:
  /dietary-reference/{country_code}:
    get:
      summary: "Retrieve dietary reference values for specified country code."
      description: "Retrieve dietary reference values for specified country code."
      produces:
      - "application/json"
      parameters:
      - name: "component_code"
        in: "query"
        description: "Food component code as specified in the EuroFIR Component Thesaurus,\
          \ listed at http://www.eurofir.org/eurofir-thesauri/."
        required: true
        type: "string"
      - name: "eng_name"
        in: "query"
        description: "Name of the user group in English."
        required: false
        type: "string"
      - name: "country_code"
        in: "path"
        description: "ISO 3166 country code of the country to return data from."
        required: true
        type: "string"
        enum: [
          "at",
          "de",
          "ch",
          "si",
          "cz",
          "uk",
          "it",
          "dk",
          "fi",
          "is",
          "no",
          "se",
          "fo",
          "gl",
          "eu"
        ]
      responses:
        200:
          description: "Returns a list of dietary reference values"
          schema:
            $ref: "#/definitions/Data"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
        500:
          description: "An internal error occurred"
        401:
          description: "Unauthorized: provide a valid API key"
        403:
          description: "Forbidden: the provided API key is invalid"
      security:
      - api_key: []
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "x-api-key"
    in: "header"
definitions:
  MetaData:
    type: "object"
    required:
    - "ageMax"
    - "ageMin"
    - "ageUnit"
    - "engName"
    - "sex"
    properties:
      reference:
        description: "Dietary value reference"
        $ref: "#/definitions/DataReference"
      engName:
        type: "string"
        description: "User group"
      sex:
        type: "string"
        description: "Sex"
        enum:
        - "M"
        - "F"
        - "M,F"
      ageMin:
        type: "integer"
        description: "Lowest age for which the dietary reference value is valid"
      ageMax:
        type: "integer"
        description: "Highest age for which the dietary reference value is valid"
      ageUnit:
        type: "string"
        description: "Unit of age (months / years)"
        enum:
        - "M"
        - "Y"
      drvs:
        type: "array"
        description: "Dietary reference values"
        items:
          $ref: "#/definitions/DietaryReferenceValue"
  DietaryReferenceValue:
    type: "object"
    properties:
      component:
        description: "Food component"
        $ref: "#/definitions/Component"
      reference:
        description: "Dietary value reference"
        $ref: "#/definitions/DataReference"
      unit:
        description: "Unit of the food component"
        $ref: "#/definitions/Unit"
      lt:
        type: "number"
        format: "double"
        description: "Lowest Threshold Intake"
      ar:
        type: "number"
        format: "double"
        description: "Average Requirement"
      pr:
        type: "number"
        format: "double"
        description: "Population Reference Intake"
      ul:
        type: "number"
        format: "double"
        description: "Upper Limit of Intake"
      valueTypeCode:
        type: "string"
        description: "Value type as specified in the EuroFIR Value Type Thesaurus"
  Data:
    type: "object"
    required:
    - "data"
    - "success"
    properties:
      data:
        type: "array"
        description: "Dietary values with basic information describing the reference"
        items:
          $ref: "#/definitions/MetaData"
      success:
        type: "boolean"
        description: "Description if request was successful"
      status:
        type: "string"
        description: "Description of what was done"
  Component:
    type: "object"
    properties:
      code:
        type: "string"
        description: "Unit code as specified in the EuroFIR Unit Thesaurus"
      description:
        type: "string"
        description: "Description of the code"
  Unit:
    type: "object"
    properties:
      code:
        type: "string"
        description: "Unit code as specified in the EuroFIR Unit Thesaurus"
      description:
        type: "string"
        description: "Description of the code"
  DataReference:
    type: "object"
    properties:
      acqType:
        type: "string"
        description: "Acquisition type as specified in the EuroFIR Acquisition Type\
          \ Thesaurus"
      referenceType:
        type: "string"
        description: "Reference type as specified in the EuroFIR Reference Type Thesaurus"
      citation:
        type: "string"
        description: "Reference’s citation"
externalDocs:
  description: "PDF documentation"
  url: /pdfs/drv.pdf
