---
swagger: "2.0"
info:
  version: "2019-08-21T08:56:55Z"
  title: "eNutri API"
host: "api.quisper.eu"
basePath: "/enutri/de-rct"
schemes:
  - "https"
paths:
  /advice:
    post:
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "FFQ Json"
          required: true
          schema:
            $ref: "#/definitions/Empty"
      responses:
        200:
          description: "Nutritional Advice Json"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
      security:
        - api_key: []
    options:
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "x-api-key"
    in: "header"
definitions:
  Empty:
    type: "object"
    title: "Empty Schema"
