---
swagger: "2.0"
info:
  description: 'SOAP web service that provides access to food composition data collected
    by EU project EuroFIR. See the PDF documentation for more information on syntax
    and allowed requests.

    The api user id mentioned in the PDF should be set to the literal `quisper` and the
    api secret key mentioned in the PDF is the literal `e_x|p1nic}fkFg~0oikxoo"$>*2jtPO@|Z@!o^I?`'
  version: "1.0.0"
  title: "EuroFIR-FoodTransport"
host: "qsp-api.thehyve.net"
basePath: "/foodtransport/beta"
schemes:
- "https"
paths:
  /food-transport:
    get:
      description: "Retrieve the WSDL specification of the EuroFIR Food Transport\
        \ SOAP service."
      produces:
      - "application/xml"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
    post:
      description: "Execute a SOAP request on the EuroFIR Food Transport SOAP service.\
        \ See the PDF documentation on the developer portal for more information."
      produces:
      - "text/xml"
      - "application/json"
      parameters:
      - name: "Content-Type"
        in: "header"
        required: true
        type: "string"
      - name: "Accept"
        in: "header"
        required: true
        type: "string"
      responses:
        200:
          description: "Response data for the service."
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        500:
          description: "Request failed."
          schema:
            $ref: "#/definitions/Empty"
        401:
          description: "Unauthorized: no API key was provided."
          schema:
            $ref: "#/definitions/Error"
        403:
          description: "Forbidden: API key was not authorized for this API."
          schema:
            $ref: "#/definitions/Error"
      security:
      - api_key: []
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "x-api-key"
    in: "header"
definitions:
  Empty:
    type: "object"
    title: "Empty Schema"
  Error:
    type: "object"
    properties:
      message:
        type: "string"
    title: "Error Schema"
externalDocs:
  description: "PDF documentation"
  url: /pdfs/FoodTransport.pdf
