---
swagger: "2.0"
info:
  description: |
    This web service for food composition data allows users to search information from most EU Member States as well as Canada and USA, simultaneously. It contains a wide range of data, linking foods and nutrients through harmonised data description (LanguaL), standardised components and value description with the use of EuroFIR thesauri (standard vocabularies) and associated nutrient value information.

    The FoodTransport service includes options to search for food by name, food groups and the most common (LanguaL)[http://www.langual.org] food description. The service has the unique ability to compare component values between foods from the several countries. Results can be downloaded as a Food Data Transport Package (FDTP).

    The provision of high quality data in the food composition databases (FCDBs) linked with EuroFIR is one of the most important goals of the network. Therefore, skilled and experienced technical experts are continuously working towards improving the content and quality of the data in their national FCDBs. The data are thoroughly documented for best possible transparency, aggregated, validated and compiled following strict and standardised quality evaluation procedures before it can be published in the national FCDBs and be available for all data users. The provision of a quality index for each value will be one of the aims of the FCDBs in the future, increasing the usefulness of the data for all users.

    Data available for use comprise data from the [national FCDBs linked with EuroFIR](http://www.eurofir.org/food-information/food-composition-databases-2/).

    ## Technical information

    EuroFIR-FoodTransport is a SOAP/XML web service that provides access to food composition data. See the PDF documentation for more information on syntax and allowed requests.

    The accompanied PDF mentions that the content of a request should include an API user ID and a signature made with a secret key. The API user ID is the literal `quisper` and the secret key is the literal `e_x|p1nic}fkFg~0oikxoo"$>*2jtPO@|Z@!o^I?`, while the `api_permission` maps to the [country codes of the partnering institutions](http://www.eurofir.org/food-information/food-composition-databases-2/). An example POST request could be
    ```
    <?xml version="1.0" encoding="utf-8" ?>
    <soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
      <soap:Header></soap:Header>
      <soap:Body>
        <GetContentInformation xmlns="http://eurofir.webservice.namespace">
          <api_permission>uk</api_permission>
          <api_userid>quisper</api_userid>
          <fdql_sentence><![CDATA[<?xml version="1.0" encoding="UTF-8"?><FDQL_Sentence><MetaData><SchemaVersion>1.2</SchemaVersion><Schema>EuroFIR_Web_Service_FDQL_Sentence_version_1_2.xsd</Schema></MetaData><SelectClause><FieldName>Content</FieldName></SelectClause></FDQL_Sentence>]]></fdql_sentence>
          <version>1.2</version>
          <api_signature>e61ae60dca26a29fb379a0b21f57b6e840f4a2e9</api_signature>
        </GetContentInformation>
      </soap:Body>
    </soap:Envelope>
    ```

    See the PDF for operations other than GetContentInformation.
  version: "1.0.0"
  title: "EuroFIR-FoodTransport"
host: "qsp-api.thehyve.net"
basePath: "/foodtransport/beta"
schemes:
- "https"
paths:
  /food-transport:
    get:
      description: "Retrieve the WSDL specification of the EuroFIR Food Transport\
        \ SOAP service."
      produces:
      - "text/xml"
      responses:
        200:
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
    post:
      description: "Execute a SOAP request on the EuroFIR Food Transport SOAP service.\
        \ See the PDF documentation on the developer portal for more information."
      consumes:
      - 'text/xml'
      produces:
      - "text/xml"
      - "application/json"
      parameters:
      - in: body
        name: SOAP
        schema:
          type: "object"
      - name: "Content-Type"
        in: "header"
        description: 'Mediatype that supports SOAP XML, e.g. text/xml.'
        required: true
        type: "string"
      - name: "Accept"
        in: "header"
        description: 'Mediatype that includes text/xml.'
        required: true
        type: "string"
      responses:
        200:
          description: "Response data for the service."
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        500:
          description: "Request failed."
        401:
          description: "Unauthorized: no API key was provided."
          examples:
            application/json: '{"message": "No API key was provided"}'
          schema:
            $ref: "#/definitions/Error"
        403:
          description: "Forbidden: API key was not authorized for this API."
          examples:
            application/json: '{"message": "API key not allowed"}'
          schema:
            $ref: "#/definitions/Error"
      security:
      - api_key: []
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "x-api-key"
    in: "header"
definitions:
  Error:
    type: "object"
    properties:
      message:
        type: "string"
    title: "Error Schema"
externalDocs:
  description: "PDF documentation"
  url: /pdfs/FoodTransport.pdf
