---
swagger: "2.0"
info:
  description: "An XML web service that provides a single-point access to QSP webservices."
  version: "1.0.0"
  title: "HarmonizedQuisper"
host: "qsp-api.thehyve.net"
basePath: "/harmonized/beta"
schemes:
- "https"
paths:
  /:
    post:
      description: "Retrieve the answer for the QDQL sentence."
      consumes:
      - "application/xml"
      produces:
      - "text/html"
      - "application/xml"
      parameters:
      - name: "Content-Type"
        in: "header"
        required: true
        type: "string"
      - name: "Accept"
        in: "header"
        required: true
        type: "string"
      - in: "body"
        name: "DQLSentence"
        description: "More information about QDQL sentence can be found in the technical\
          \ report of the HarmonizedQusiper."
        required: true
        schema:
          $ref: "#/definitions/DQLSentence"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        500:
          description: "500 response"
          schema:
            $ref: "#/definitions/Empty"
        415:
          description: "415 response"
          schema:
            $ref: "#/definitions/Empty"
        406:
          description: "406 response"
          schema:
            $ref: "#/definitions/Empty"
      security:
      - api_key: []
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "x-api-key"
    in: "header"
definitions:
  Empty:
    type: "object"
    title: "Empty Schema"
  DQLSentence:
    type: "object"
    description: "More information about QDQL sentence can be found in the technical\
      \ report of the HarmonizedQusiper."
    title: "DQL_Sentence"
    example:
      MetaData:
        SchemaVersion: 1.2
        Schema: QDQL_Sentence_version_1_0.xsd
      SelectClause:
        FieldName: FoodName
    required:
     - MetaData
    properties:
     MetaData:
      type: object
      required:
       - SchemaVersion
       - Schema
      properties:
       SchemaVersion:
        description: "Version number, e.g., 1.2."
        type: string
       Schema:
        description: "Schema name, e.g. QDQL_Sentence_version_1_0.xsd"
        type: string
     SelectClause:
      type: object
      properties:
       FieldName:
        type: string
     WhereClause:
      type: object
      properties:
       Condition:
        type: object
        properties:
         ClassificationConditionField:
          type: string
         ConditionOperator:
          type: string
         ConditionValue:
          type: string
     OrderByClause:
      type: object
      properties:
       OrderByField:
        type: string
externalDocs:
  description: "PDF documentation"
  url: /pdfs/HarmonizedQuisper.pdf
