---
swagger: "2.0"
info:
  version: "2020-07-17T13:26:53Z"
  title: "FoodEXplorer-v0.1"
host: "api.quisper.eu"
basePath: "/fdtp/alpha"
schemes:
  - "https"
paths:
  /foodexplorer/food-code/{food-code}:
    get:
      produces:
        - "application/json"
      parameters:
        - name: "food-code"
          in: "path"
          required: true
          type: "string"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
      security:
        - api_key: []
    options:
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /foodexplorer/food-name/{food-name}:
    get:
      produces:
        - "application/json"
      parameters:
        - name: "food-name"
          in: "path"
          required: true
          type: "string"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
      security:
        - api_key: []
    options:
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /foodexplorer/nutritional-value/{foodcode}:
    get:
      produces:
        - "application/json"
      parameters:
        - name: "foodcode"
          in: "path"
          required: true
          type: "string"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
      security:
        - api_key: []
    options:
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /foodexplorer/{type}:
    get:
      produces:
        - "application/json"
      parameters:
        - name: "type"
          in: "path"
          required: true
          description: "Name of the query."
          type: "string"
          enum: [
            "getAcquisitionType",
            "getComponent",
            "getCookingMet",
            "getCountry",
            "getFoodGroup",
            "getMatrix",
            "getMethodIndicator",
            "getMethodIype",
            "getReferenceType",
            "getUnit",
            "getValueType"
          ]
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
      security:
        - api_key: []
    options:
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "x-api-key"
    in: "header"
definitions:
  Empty:
    type: "object"
    title: "Empty Schema"